#if UNITY_EDITOR
using System;
using System.Collections.Generic;

/// <summary>
/// German launch translations. Kept separate from the legacy six-column catalog so
/// the already-authored zh-Hans source and generated assets remain available for a
/// future re-enable without being part of the current production locale set.
/// </summary>
internal static class SkateLocalizationGermanCatalog
{
    private static readonly IReadOnlyDictionary<string, string> Values =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["common.ok"] = "OK",
            ["common.yes"] = "JA",
            ["common.no"] = "NEIN",
            ["common.back"] = "ZURÜCK",
            ["common.close"] = "SCHLIESSEN",
            ["common.free"] = "GRATIS",
            ["common.watch"] = "ANSEHEN",
            ["common.claim"] = "ABHOLEN",
            ["common.claimed"] = "ABGEHOLT",
            ["common.locked"] = "GESPERRT",
            ["common.owned"] = "IM BESITZ",
            ["common.equip"] = "AUSRÜSTEN",
            ["common.equipped"] = "AUSGERÜSTET",
            ["common.coming_soon"] = "DEMNÄCHST",
            ["common.resets_in"] = "RESET IN {0}",
            ["common.ends_in"] = "ENDET IN {0}",
            ["common.claim_in"] = "ABHOLEN IN {0}",
            ["common.utc_reset"] = "UTC-RESET {0}",
            ["common.legendary"] = "LEGENDÄR",
            ["common.default"] = "STANDARD",
            ["common.bonus"] = "BONUS",

            ["home.play"] = "SPIELEN",
            ["home.home"] = "HOME",
            ["home.inventory"] = "INVENTAR",
            ["home.missions"] = "MISSIONEN",
            ["home.rewards"] = "BELOHNUNGEN",
            ["home.shop"] = "SHOP",
            ["home.no_ads"] = "WERBEFREI",
            ["home.free_cash"] = "GRATIS-CASH",
            ["home.spin"] = "DREHEN",
            ["home.level"] = "LEVEL {0}",
            ["home.spin_action"] = "DREHEN!",
            ["home.lucky_spin"] = "Glücksrad",
            ["home.daily_spin"] = "Täglicher Dreh",

            ["shop.title"] = "SHOP",
            ["shop.swords"] = "SCHWERTER",
            ["shop.abilities"] = "FÄHIGKEITEN",
            ["shop.rollerblades"] = "INLINESKATES",
            ["shop.currency_pack"] = "WÄHRUNGSPAKET",
            ["shop.cash"] = "CASH",
            ["shop.gems"] = "JUWELEN",
            ["shop.chest"] = "TRUHE",
            ["shop.special"] = "SPEZIAL",
            ["shop.lucky_chest"] = "Glückstruhe",
            ["shop.epic_chest"] = "Epische Truhe",
            ["shop.best_value"] = "Bestes Angebot",
            ["shop.double_value"] = "2x Wert",
            ["shop.confirm_purchase"] = "KAUF BESTÄTIGEN",
            ["shop.purchase_complete"] = "KAUF ABGESCHLOSSEN!",
            ["shop.not_enough_gems"] = "NICHT GENUG JUWELEN",
            ["shop.not_enough_cash"] = "NICHT GENUG CASH",
            ["shop.unavailable"] = "NICHT VERFÜGBAR",
            ["shop.confirm_gems"] = "Du gibst gleich {0} Juwelen für {1} aus. Fortfahren?",
            ["shop.confirm_cash"] = "Du gibst gleich {0} Cash für {1} aus. Fortfahren?",
            ["shop.confirm_real_money"] = "Du gibst gleich {0} für {1} aus. Fortfahren?",
            ["shop.need_more_gems"] = "Dir fehlen {0} Juwelen für {1}.",
            ["shop.need_more_cash"] = "Dir fehlen {0} Cash für {1}.",

            ["inventory.title"] = "INVENTAR",
            ["inventory.swords"] = "SCHWERTER",
            ["inventory.abilities"] = "FÄHIGKEITEN",
            ["inventory.rollerblades"] = "INLINESKATES",
            ["inventory.preview"] = "VORSCHAU",
            ["inventory.equip"] = "AUSRÜSTEN",
            ["inventory.equipped"] = "AUSGERÜSTET",

            ["missions.title"] = "MISSIONEN",
            ["missions.daily"] = "TÄGLICHE MISSIONEN",
            ["missions.story"] = "STORY-MISSIONEN",
            ["missions.mafia_board"] = "MAFIA-TAFEL",
            ["missions.collect_cash.title"] = "CASH SAMMELN",
            ["missions.collect_gems.title"] = "JUWELEN SAMMELN",
            ["missions.cross_levels.title"] = "LEVEL ABSCHLIESSEN",
            ["missions.ad_break.title"] = "WERBEPAUSE",
            ["missions.collect_cash.description"] = "Sammle {0} Cash",
            ["missions.collect_gems.description"] = "Sammle {0} Juwelen",
            ["missions.complete_levels.description"] = "Schließe {0} Level ab",
            ["missions.watch_ads.description"] = "Sieh dir {0} Werbungen an",
            ["missions.kill_enemies"] = "Besiege {0:N0} Gegner",
            ["missions.earn_cash"] = "Verdiene {0:N0} Cash",
            ["missions.survive_seconds"] = "Überlebe {0:N0} {0:plural:Sekunde|Sekunden}",
            ["missions.down_attack_kills"] = "Besiege {0:N0} Gegner mit Sturzangriffen",
            ["missions.dash_attack_kills"] = "Besiege {0:N0} Gegner mit Sprintangriffen",
            ["missions.use_power_slam"] = "Setze Power Slam {0:N0}-mal ein",
            ["missions.phase2_combo"] = "Erreiche eine {0:N0}er-Kombo in Phase 2",
            ["missions.phase2_cash"] = "Verdiene {0:N0} Cash in Phase 2",
            ["missions.phase2_no_fail"] = "Schließe Phase 2 fehlerfrei ab",
            ["missions.progress"] = "{0} ({1}/{2})",

            ["rewards.title"] = "BELOHNUNGEN",
            ["rewards.daily"] = "TÄGLICHE BELOHNUNGEN",
            ["rewards.tomorrow"] = "Morgen",
            ["rewards.tomorrow_item"] = "Item von morgen",
            ["rewards.resets_in_label"] = "Reset in:",
            ["rewards.day_1"] = "TAG 1",
            ["rewards.day_2"] = "TAG 2",
            ["rewards.day_3"] = "TAG 3",
            ["rewards.day_4"] = "TAG 4",
            ["rewards.day_5"] = "TAG 5",
            ["rewards.day_6"] = "TAG 6",
            ["rewards.day_7"] = "TAG 7",
            ["rewards.chest_x1"] = "Truhe x1",
            ["rewards.special_chest_x1"] = "Spezialtruhe x1",
            ["rewards.lucky_chest_x3"] = "Glückstruhe <size=50>x3</size>",
            ["rewards.day"] = "TAG {0}",
            ["rewards.cash"] = "{0} Cash",
            ["rewards.gems"] = "{0} Juwelen",
            ["rewards.cash_and_gems"] = "{0} Cash + {1} Juwelen",
            ["rewards.chest"] = "Truhe x{0}",
            ["rewards.special_chest"] = "Spezialtruhe x{0}",
            ["rewards.unlocked"] = "BELOHNUNG FREIGESCHALTET!",
            ["rewards.new_item"] = "NEUES ITEM FREIGESCHALTET!",
            ["rewards.purchase_complete"] = "KAUF ABGESCHLOSSEN!",
            ["rewards.you_won"] = "DU HAST GEWONNEN!",
            ["rewards.spins_left"] = "Noch {0}",
            ["rewards.result_cash"] = "+{0} Cash",
            ["rewards.result_gems"] = "+{0} Juwelen",

            ["settings.title"] = "EINSTELLUNGEN",
            ["settings.general"] = "ALLGEMEIN",
            ["settings.audio"] = "AUDIO",
            ["settings.display"] = "ANZEIGE",
            ["settings.music"] = "Musik",
            ["settings.sound_effects"] = "Soundeffekte",
            ["settings.vibration"] = "Vibration",
            ["settings.graphics_quality"] = "Grafikqualität",
            ["settings.auto"] = "AUTO",
            ["settings.low"] = "NIEDRIG",
            ["settings.high"] = "HOCH",
            ["settings.language"] = "SPRACHE",
            ["settings.privacy_legal"] = "DATENSCHUTZ & RECHTLICHES",
            ["settings.follow_us"] = "FOLGE UNS",
            ["settings.version"] = "Version {0}",

            ["gameplay.pause"] = "PAUSE",
            ["gameplay.paused"] = "PAUSIERT",
            ["gameplay.resume"] = "FORTSETZEN",
            ["gameplay.restart"] = "NEUSTART",
            ["gameplay.restart_level"] = "LEVEL NEU STARTEN",
            ["gameplay.main_menu"] = "HAUPTMENÜ",
            ["gameplay.revive"] = "WIEDERBELEBEN",
            ["gameplay.no_thanks"] = "Nein, danke",
            ["gameplay.level_completed"] = "LEVEL ABGESCHLOSSEN",
            ["gameplay.level_failed"] = "LEVEL FEHLGESCHLAGEN",
            ["gameplay.you_died"] = "DU BIST GESTORBEN!",
            ["gameplay.game_over"] = "Game Over",
            ["gameplay.seconds"] = "{0} s",
            ["gameplay.continue"] = "Weiter",
            ["gameplay.combo"] = "Kombo",
            ["gameplay.timer"] = "Timer",
            ["gameplay.loading"] = "WIRD GELADEN...",
            ["gameplay.phase_1"] = "PHASE 1",
            ["gameplay.phase_2"] = "PHASE 2",

            ["tutorial.left"] = "Links",
            ["tutorial.right"] = "Rechts",
            ["tutorial.main_action"] = "Hauptaktionstaste",

            ["popups.remove_ads_question"] = "Möchtest du Werbung entfernen?",
            ["popups.later"] = "Später",
            ["popups.daily_free_cash"] = "TÄGLICHES GRATIS-CASH",
            ["popups.wait"] = "BITTE WARTEN...",

            ["items.ability.fire"] = "Feuer",
            ["items.ability.ice"] = "Eis",
            ["items.ability.electricity"] = "Elektrizität",
            ["items.ability.poison"] = "Gift",
            ["items.ability.magic"] = "Magie",
            ["items.ability.fire_power"] = "Feuerkraft",
            ["items.ability.ice_power"] = "Eiskraft",
            ["items.ability.electricity_power"] = "Elektrokraft",
            ["items.ability.poison_power"] = "Giftkraft",
            ["items.ability.magic_power"] = "Magiekraft",
            ["items.sword.katana"] = "Katana",
            ["items.rollerblade.default"] = "Standard-Inlineskates",
            ["items.sword.bloodreaver"] = "BloodReaver",
            ["items.sword.emberguard"] = "Emberguard",
            ["items.sword.hellforge"] = "HellForge",
            ["items.sword.gravebreaker"] = "Gravebreaker",
            ["items.sword.glacier_cipher"] = "Glacier Cipher",
            ["items.sword.wyrmshade"] = "Wyrmshade",
            ["items.sword.sunspire"] = "Sunspire",
            ["items.rollerblade.urbanrush"] = "UrbanRush",
            ["items.rollerblade.neonvelocity"] = "NeonVelocity",
            ["items.rollerblade.frostbiteglide"] = "FrostbiteGlide",
            ["items.rollerblade.infernodrift"] = "InfernoDrift",
            ["items.rollerblade.celestialapex"] = "CelestialApex",
            ["items.rollerblade.energen"] = "Energen",
            ["items.rollerblade.firo"] = "Firo",

            ["legal.privacy_policy"] = "DATENSCHUTZERKLÄRUNG",
            ["legal.terms_of_use"] = "NUTZUNGSBEDINGUNGEN",
            ["legal.eula"] = "ENDBENUTZER-LIZENZVERTRAG",
            ["legal.data_deletion"] = "DATEN- & LÖSCHANFRAGE",
            ["legal.restore_purchases"] = "KÄUFE WIEDERHERSTELLEN",
            ["legal.support"] = "SUPPORT",
            ["legal.privacy_coming_soon"] = "Die Datenschutzerklärung folgt in Kürze.",
            ["legal.terms_coming_soon"] = "Die Nutzungsbedingungen folgen in Kürze.",
            ["legal.eula_coming_soon"] = "Der Endbenutzer-Lizenzvertrag folgt in Kürze.",
            ["legal.data_coming_soon"] = "Daten- und Löschanfragen folgen in Kürze.",
            ["legal.restore_unavailable"] = "Die Wiederherstellung von Käufen ist noch nicht verfügbar.",
            ["legal.support_coming_soon"] = "Der Supportkontakt folgt in Kürze."
        };

    internal static string GetRequired(string key)
    {
        if (Values.TryGetValue(key, out string value) && !string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        throw new InvalidOperationException("Missing German localization for key: " + key);
    }
}
#endif
